export const SET_LOCATION = 'SET_LOCATION';
export const MAKE_LOCATION_FAVOURITE = 'MAKE_LOCATION_FAVOURITE';
export const RENOUNCE_LOCATION_FAVOURITE = 'RENOUNCE_LOCATION_FAVOURITE';

export const ADD_FAVOURITE_LOCATION = 'ADD_FAVOURITE_LOCATION';
export const REMOVE_FAVOURITE_LOCATION = 'REMOVE_FAVOURITE_LOCATION';

export const RESET_START_LOCATION = 'RESET_START_LOCATION';
export const SET_START_LOCATION = 'SET_START_LOCATION';

export const ADD_LOCATION_SEARCH = 'ADD_LOCATION_SEARCH';
